module.exports = {
	rules: {
		'array-bracket-newline': 'off',
		'array-bracket-spacing': 'off',
		'array-element-newline': ['error', 'consistent' ],
		'arrow-parens': 'off',
		'arrow-spacing': ['error', { before: true, after: true }],
		'block-spacing': ['error', 'always'],
		'brace-style': ['error', '1tbs', { allowSingleLine: true }],
		'comma-dangle': ['error', 'always-multiline'],
		'comma-spacing': ['error', { before: false, after: true }],
		'comma-style': ['error', 'last'],
		'computed-property-spacing': ['error', 'never'],
		'dot-location': ['error', 'property'],
		'eol-last': ['error', 'always'],
		'func-call-spacing': ['error', 'never'],
		'function-call-argument-newline': 'off',
		'function-paren-newline': 'off',
		'generator-star-spacing': 'off',
		'implicit-arrow-linebreak': ['error', 'beside'],
		'indent': ['error', 'tab', { SwitchCase: 1 }],
		'jsx-quotes': 'off',
		'key-spacing': ['error', { beforeColon: false, afterColon: true }],
		'keyword-spacing': ['error', { before: true, after: true }],
		'line-comment-position': 'off',
		'linebreak-style': ['error', 'unix'],
		'lines-around-comment': 'off',
		'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: false }],
		'max-len': 'off',
		'max-statements-per-line': 'off',
		'multiline-ternary': ['error', 'always-multiline'],
		'new-parens': 'error',
		'newline-per-chained-call': ['error', { ignoreChainWithDepth: 4 }],
		'no-extra-parens': 'off',
		'no-mixed-spaces-and-tabs': 'error',
		'no-multi-spaces': ['error', { ignoreEOLComments: false }],
		'no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 0 }],
		'no-tabs': 'off',
		'no-trailing-spaces': ['error', { skipBlankLines: false, ignoreComments: false }],
		'no-whitespace-before-property': 'error',
		'nonblock-statement-body-position': ['error', 'beside', { overrides: {} }],
		'object-curly-newline': ['error', { minProperties: 4, consistent: true }],
		'object-curly-spacing': ['error', 'always'],
		'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
		'operator-linebreak': 'off',
		'padded-blocks': ['error', 'never', { allowSingleLineBlocks: true }],
		'padding-line-between-statements': 'off',
		'quotes': ['error', 'single', { avoidEscape: true }],
		'rest-spread-spacing': ['error', 'never'],
		'semi': ['error', 'always'],
		'semi-spacing': ['error', { before: false, after: true }],
		'semi-style': ['error', 'last'],
		'space-before-blocks': ['error', 'always'],
		'space-before-function-paren': ['error', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
		'space-in-parens': ['error', 'never'],
		'space-infix-ops': 'error',
		'space-unary-ops': ['error', { words: true, nonwords: false }],
		'switch-colon-spacing': ['error', { after: true, before: false }],
		'template-tag-spacing': ['error', 'never'],
		'unicode-bom': ['error', 'never'],
		'wrap-iife': ['error', 'outside', { functionPrototypeMethods: false }],
		'wrap-regex': 'off',
		'yield-star-spacing': 'off',
	},
};
