module.exports = {
	rules: {
		'array-bracket-newline': 'off',
		'array-bracket-spacing': 'off',
		'array-element-newline': ['error', 'consistent' ],
		'block-spacing': ['error', 'always'],
		'brace-style': ['error', '1tbs', { allowSingleLine: true }],
		'camelcase': 'off',
		'capitalized-comments': 'off',
		'comma-dangle': ['error', 'always-multiline'],
		'comma-spacing': ['error', { before: false, after: true }],
		'comma-style': ['error', 'last'],
		'computed-property-spacing': ['error', 'never'],
		'consistent-this': 'off',
		'eol-last': ['error', 'always'],
		'func-call-spacing': ['error', 'never'],
		'func-name-matching': 'off',
		'func-names': 'warn',
		'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
		'function-call-argument-newline': 'off',
		'function-paren-newline': 'off',
		'id-denylist': 'off',
		'id-length': 'off',
		'id-match': 'off',
		'implicit-arrow-linebreak': ['error', 'beside'],
		'indent': ['error', 'tab', { SwitchCase: 1 }],
		'jsx-quotes': 'off',
		'key-spacing': ['error', { beforeColon: false, afterColon: true }],
		'keyword-spacing': ['error', { before: true, after: true }],
		'line-comment-position': 'off',
		'linebreak-style': ['error', 'unix'],
		'lines-around-comment': 'off',
		'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: false }],
		'max-depth': 'off',
		'max-len': 'off',
		'max-lines-per-function': 'off',
		'max-lines': 'off',
		'max-nested-callbacks': 'off',
		'max-params': 'off',
		'max-statements-per-line': 'off',
		'max-statements': 'off',
		'multiline-comment-style': ['off', 'starred-block'],
		'multiline-ternary': ['error', 'always-multiline'],
		'new-cap': 'off',
		'new-parens': 'error',
		'newline-per-chained-call': ['error', { ignoreChainWithDepth: 4 }],
		'no-array-constructor': 'error',
		'no-bitwise': 'warn',
		'no-continue': 'off',
		'no-inline-comments': 'off',
		'no-lonely-if': 'error',
		'no-mixed-operators': 'off',
		'no-mixed-spaces-and-tabs': 'error',
		'no-multi-assign': 'off',
		'no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 0 }],
		'no-negated-condition': 'off',
		'no-nested-ternary': 'off',
		'no-new-object': 'error',
		'no-plusplus': 'off',
		'no-restricted-syntax': 'off',
		'no-tabs': 'off',
		'no-ternary': 'off',
		'no-trailing-spaces': ['error', { skipBlankLines: false, ignoreComments: false }],
		'no-underscore-dangle': 'off',
		'no-unneeded-ternary': ['error', { defaultAssignment: true }],
		'no-whitespace-before-property': 'error',
		'nonblock-statement-body-position': ['error', 'beside', { overrides: {} }],
		'object-curly-newline': ['error', { minProperties: 4, consistent: true }],
		'object-curly-spacing': ['error', 'always'],
		'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
		'one-var-declaration-per-line': ['error', 'always'],
		'one-var': ['error', 'never'],
		'operator-assignment': 'off',
		'operator-linebreak': 'off',
		'padded-blocks': ['error', 'never', { allowSingleLineBlocks: true }],
		'padding-line-between-statements': 'off',
		'prefer-exponentiation-operator': 'error',
		'prefer-object-spread': 'off',
		'quote-props': ['error', 'as-needed'],
		'quotes': ['error', 'single', { avoidEscape: true }],
		'semi-spacing': ['error', { before: false, after: true }],
		'semi-style': ['error', 'last'],
		'semi': ['error', 'always'],
		'sort-keys': 'off',
		'sort-vars': 'off',
		'space-before-blocks': ['error', 'always'],
		'space-before-function-paren': ['error', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
		'space-in-parens': ['error', 'never'],
		'space-infix-ops': 'error',
		'space-unary-ops': ['error', { words: true, nonwords: false }],
		'spaced-comment': 'off',
		'switch-colon-spacing': ['error', { after: true, before: false }],
		'template-tag-spacing': ['error', 'never'],
		'unicode-bom': ['error', 'never'],
		'wrap-regex': 'off',
	},
};
